name: run-renovate
run-name: Renovate
on:
  push:
    branches:
      - "main"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache
        id: cache-renovate
        uses: actions/cache@v4
        with:
          path: /tmp/renovate/cache
          key: cache-renovate
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.2
        with:
          configurationFile: .github/renovate.json
          docker-user: root
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
